name: CI - Verificaciones TFG

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # 1. Apartado de Estructura y Frontend (HTML/Typescript/Format)
  calidad_estructura:
    name: 'Calidad: Estructura y Formato'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Instalación Limpia
        run: npm ci
      - name: Verificar Formato (Prettier)
        run: npx prettier --check src .github

  # 2. Apartado de Diseno y Estilos (CSS)
  calidad_estilos:
    name: 'Calidad: Estilos y Diseno (CSS)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Instalacion Limpia
        run: npm ci
      - name: Verificar Lint de CSS
        run: npx prettier --check "src/**/*.css"

  # 3. Apartado de Logica y Mapas (Tests Unitarios)
  logica_funcionalidad:
    name: 'Logica: Simulador y Mapas'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Instalacion Limpia
        run: npm ci
      - name: Ejecutar Tests de Logica (Vitest)
        run: npx vitest run --config vitest.config.mts

  # 4. Apartado de Compilación Final
  build_proyecto:
    name: 'Build: Compilación Global'
    runs-on: ubuntu-latest
    needs: [calidad_estructura, calidad_estilos, logica_funcionalidad]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Instalación Limpia
        run: npm ci
      - name: Compilar Proyecto Angular
        run: npm run build
